title: Cantella
description: "Study Site for DNHS"
owner_name: Xavier Thompson
github_username: XavierTho
github_repo: "cantella_frontend" 
baseurl: "/cantella_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/profiles.md
  - navigation/calendar.md
  - navigation/tutor.html
  - navigation/flashcards.md
  - navigation/studylog.md
  - navigation/gradelog.md
  - navigation/deployment.md
  - navigation/about.md



Server: https://cantella.nighthawkcodingsociety.com/
Domain: nighthawkcodingsociety.com
Subdomain: cantella